spring:
  application:
    name: user-service-api

  data:
    mongodb:
      uri: mongodb+srv://saedsousa:saedsousa@cluster0.600aigh.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

server:
  port: 8090